config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "tweets#index"
  resources :tweets do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user
  has_many :comments

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    redirect_to "/tweets/#{comment.tweet.id}" 
  end

  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
    redirect_to root_path
    else
      render 'new'
  end
end

  def destroy
    @tweet.destroy if @tweet.user_id == current_user.id
  end

  def edit
    if user_signed_in? && current_user.id == @tweet.user_id
      @tweet = Tweet.find(params[:id])
    else user_signed_in?
      redirect_to(root_path)
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.user_id == current_user.id
      @tweet.update(tweet_params)
  end
end

  def show
    @comments = @tweet.comments.includes(:user)
  end

  private
  def tweet_params
    params.permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  user = User.find(params[:id])
  @nickname = user.nickname
  @tweets = user.tweets.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pictweet
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    :javascript
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
  %body
    %header.header
      .header__bar.row
        %h1.grid-6
          %a{:href => "/"} SNSTweet
        - if user_signed_in?
          .user_nav.grid-6
            %span
              = current_user.nickname
              %ul.user__info
                %li
                  %a{:href => "/users/#{current_user.id}"} マイページ
                  = link_to "ログアウト", destroy_user_session_path, method: :delete
            %a.post{:href => "/tweets/new"} 投稿する
        - else
          .grid-6
            = link_to "ログイン", new_user_session_path, class: 'post'
            = link_to "新規登録", new_user_registration_path, class: 'post'
    = yield
    %footer
      %p
        Copyright SNSTweet 2019.

app/views/tweets/_tweet.html.haml
.content_post{:style => "background-image: url(#{tweet.image});"}
  %script{:src => "sample.js"}
  .more
    %span= image_tag 'arrow_top.png'
    %ul.more_list
      %li
        = link_to "詳細", tweet_path(tweet.id), method: :get
      - if user_signed_in? && current_user.id == tweet.user_id
        %li
          = link_to '編集', "/tweets/#{tweet.id}/edit", method: :get
        %li
          = link_to '削除', "/tweets/#{tweet.id}", method: :delete
  = simple_format(tweet.text)
  %span.name
    %a{:href => "/users/#{tweet.user_id}"}
      %span 投稿者
      = tweet.user.nickname

app/views/tweets/_tweet.thml.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
  <div class="more">
    <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
      <li>
        <%= link_to "詳細", tweet_path(tweet.id), method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= simple_format(tweet.text) %>
  <span class="name">
    <a href="/users/<%= tweet.user_id %>">
      <span>投稿者</span><%= tweet.user.nickname %>
    </a>
  </span>
</div>

app/views/tweets/create.html.haml
.contents.row
  .success
    %h3
      投稿が完了しました。
    %a.btn{:href => "/tweets"} 投稿一覧へ戻る

app/views/tweets/destroy.html.haml
.contents.row
  .success
    %h3
      削除が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/tweets/edit.html.haml
.contents.row
  .contents.row
  = form_tag("/tweets/#{@tweet.id}", method: :patch ) do
    %h3
      編集する
    %input{:autofocus => "true", :name => "image", :placeholder => "Image Url", :type => "file", :value => "#{@tweet.image}"}/
    %textarea{:cols => "30", :name => "text", :placeholder => "text", :rows => "10"}= @tweet.text
    %input{:type => "submit", :value => "SENT"}/

app/views/tweets/index.html.haml
.contents.row
  - @tweets.each do |tweet|
    = render partial: "tweet", locals: { tweet: tweet }
  = paginate(@tweets)

app/views/tweets/new.html.haml
.contents.row
  .container
    = form_with url: '/tweets' do |f|
      %h3
        投稿する
      = f.label :image, class: 'container__mask__image' do
        = fa_icon 'picture-o', class: 'icon'
        = f.file_field :image, class: 'hidden'
      = f.text_field :text, class: 'form__message', placeholder: 'コメント欄'
      = f.submit 'Send', class: 'form__submit'

app/views/tweets/show.html.haml
.contents.row
  .content_post{:style => "background-image: url(#{@tweet.image});"}
    - if user_signed_in? && current_user.id == @tweet.user_id
      .more
        %span= image_tag 'arrow_top.png'
        %ul.more_list
          %li
            = link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get
          %li
            = link_to '削除', "/tweets/#{@tweet.id}", method: :delete
    = simple_format(@tweet.text)
    %span.name
      %a{:href => "/users/#{@tweet.user.id}"}
        %span 投稿者
        = @tweet.user.nickname
  .container
    - if current_user
      = form_tag("/tweets/#{@tweet.id}/comments", method: :post) do
        %textarea{:cols => "30", :name => "text", :placeholder => "コメントする", :rows => "2"}
        %input{:type => "submit", :value => "SENT"}/
    .comments
      %h4 ＜コメント一覧＞
      - if @comments
        - @comments.each do |comment|
          %p
            %strong
              = link_to comment.user.nickname, "/users/#{comment.user_id}"
              ：
            = comment.text

app/views/tweets/update.html.haml
.contents.row
  .success
    %h3
      更新が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/users/show.html.haml
.contents.row
  %p
    = @nickname
    さんの投稿一覧
  - @tweets.each do |tweet|
    = render partial: "tweets/tweet", locals: { tweet: tweet }
  = paginate(@tweets)